### ISSUE TITLE
Parsing raw data

### ISSUE THREAD

**Issue by shikokuchuo** [coolbutuseless/yyjsonr#1]
Thanks for this! Definitely as cool as it gets for 'json' data.

From my perspective, the only real comparison is with `RcppSimdJson`. It's nice to say it's much faster than `jsonlite` but it's probably the other reasons why people continue to use it (proven track record, good enough etc.)

From a programming perspective, I'd like this package to be as predictable (and fast) as possible in terms of return types rather than trying to provide heuristic guesses. I think this also fits in with the philosophy of the 'yyjson' library.

Quick benchmarking shows that on small data (tens of microseconds to parse), `RcppSimdJson` slightly faster, whilst `yyjsonr` is faster on larger data (hundreds of microseconds). This is already very impressive indeed!

Just an initial query at this point - is it possible to parse a raw instead of character vector? RcppSimdJson is the same speed on either, maybe even slightly faster on raw. It is nice as it means the incoming data does not need converting in the first place - the rough equivalent of a `rawToChar()` operation.

Example:

``` r
a <- nanonext::ncurl("https://postman-echo.com/get", convert = FALSE)
a
RcppSimdJson::fparse(a[["raw"]])

b <- nanonext::ncurl("https://postman-echo.com/get", convert = TRUE)
b
yyjsonr::from_json_str(b[["data"]])
```

**Comment by coolbutuseless** [comment]
Thanks for the examples - that's a big help!

I'll look into this for next release.

**Comment by coolbutuseless** [comment]
Added a `from_json_raw()` in v0.1.1 f833b4e

Also removed some start-up overhead when handling options.  This should make `{yyjsonr}` quicker than before for small data.

Let me know how this goes for you...

**Comment by shikokuchuo** [comment]
Wow. that is quite some faster...

I'm really glad you picked up on the speed point as well.

To provide some more context, those large payloads tend to be fetching initial states which can be performed asynchronously - and speed is typically not crucial. However further updates can be on the 10-100 millisecond timescale - and these will be small (tiny) json payloads - but in fact this is where speed becomes critical.

`from_json_raw()` works as expected.

Would love to see this get to CRAN!

**Comment by coolbutuseless** [comment]
> Wow. that is quite some faster...
Your feedback made me realise the issue was startup overhead. Thanks!


> `from_json_raw()` works as expected.
👍


> Would love to see this get to CRAN!
That's the plan! Thanks for the feedback!
