### ISSUE TITLE
Feature Request: Unboxing nuance

### ISSUE THREAD

**Issue by gergness** [coolbutuseless/yyjsonr#12]
This looks like a great package! One thing that annoys me about working with JSON in R is the inability to distinguish between scalars and length-1 vectors. I often find myself working with APIs that are picky about the difference.

Right now, I think yyjsonr's `auto_unbox` behavior is all-or-nothing. jsonlite has a nice feature where you can override `auto_unbox` by using R's `as-is` class (`I()`).

What jsonlite does not do (and as far as I know [no public R package does](https://mastodon.social/@klmr/111052791317686818)) is annotate the differences between a scalar and length 1 vector at read time (via some class or other attribute metadata). This means that to round trip a JSON object, I have to manually go through the R object and add the `as-is` class (with pre-knowledge about where it belongs).

Does this fit in with the vision of yyjsonr, or would it sacrifice too much speed? If I find time, would you consider a PR? 

```r
# both jsonlite and yyjsonr can unbox none or all length 1 vectors
list(a = 1L, b = 1L) |> jsonlite::toJSON()
#> {"a":[1],"b":[1]} 
list(a = 1L, b = 2L) |> yyjsonr::write_json_str() |> cat()
#> {"a":[1],"b":[1]} 

list(a = 1L, b = 2L) |>  yyjsonr::write_json_str(auto_unbox = TRUE) |> cat()
#> {"a":1,"b":1} 
list(a = 1L, b = 1L) |> jsonlite::toJSON(auto_unbox = TRUE)
#> {"a":1,"b":1} 


# jsonlite has a way to override auto-unboxing using `I()` (the as-is class):
list(a = 1L, b = I(2L)) |> jsonlite::toJSON(auto_unbox = TRUE)
#> {"a":1,"b":[1]} 

# I think yyjsonr does not (yet?):
list(a = 1L, b = I(2L)) |>  yyjsonr::write_json_str(auto_unbox = TRUE) |> cat()
#> {"a":1,"b":2}


# In addition, I think yyjsonr could improve upon jsonlite's API because when trying to roundtrip
# it requires information that's not possible to know from its API (and can be tedious to add)
set_boxes <- \(x, names) modifyList(x, lapply(x[names], I))

'{"a": 1, "b": [2], "c": [3, 4]}' |> 
    jsonlite::fromJSON() |> 
    set_boxes("b") |> 
    jsonlite::toJSON(auto_unbox = TRUE)
#> {"a":1,"b":[2],"c":[3,4]} 



# What I hope yyjsonr could do (proposed new option named `box_singletons`?)
'{"a": 1, "b": [2], "c": [3, 4]}' |> 
    yyjsonr::read_json(box_singletons = TRUE) |> 
    str()
#> List of 3
#>  $ a: int 1
#>  $ b: 'AsIs' int 2
#>  $ c: int [1:2] 3 4


# And then I'd be able to round trip:
'{"a": 1, "b": [2], "c": [3, 4]}' |> 
    yyjsonr::read_json(box_singletons = TRUE) |> 
    yyjsonr::write_json_str(auto_unbox = TRUE) |> 
    cat()
#> {"a":1,"b":[2],"c":[3,4]}
```

Also it occurs to me that while I'm used to using `I()` to prevent `auto_unbox`ing, jsonlite actually recommends using explicitly `jsonlite::unbox()` to add `scalar` class to scalars. I don't have a preference for which way it should work in yyjsonr (or if both should be supported).

```
set_unboxes <- \(x, names) modifyList(x, lapply(x[names], jsonlite::unbox))

'{"a": 1, "b": [2], "c": [3, 4]}' |> 
    jsonlite::fromJSON() |> 
    set_unboxes("a") |> 
    jsonlite::toJSON()
 #> {"a":1,"b":[2],"c":[3,4]}
```

**Comment by gergness** [comment]
An example use case:

I work on rcrunch, which is an R client for survey data analyses stored in the cloud. We might have an analysis saved in our API with an object like:
```
{
   "analysis": {"variable": "a"},
   "web_only_display_settings": {
       "x_min": 1,
       "x_max": 2,
       "measures": ["percent"]
    }
}
```

The R client may know enough to be able to change `analysis.variable` and want to PATCH a new analysis variable but keep the `web_only_display_settings` unchanged.

As it stands, there is no way to avoid changing the structure unless I manually annotate that `x_min` and `x_max` are scalars, but `measures` is an array. This may mean that the R client has to keep knowledge about settings that don't apply to it.

I don't know if this is a a common API pattern or a quirk of our system, but often I can work around this because our API interprets a missing key at the top level as meaning "don't change". However, (in our API conventions) this does not apply after the first level, so if the settings are deeply nested, I can't always get around it.

**Comment by coolbutuseless** [comment]
This would be possible, and worth exploring. 

* support serializing scalar values as length-1 JSON arrays (instead of JSON scalar values) if they are wrapped in `I()` call.  i.e. have `AsIs` class.   This could mimic the behaviour of jsonlite?
* tag scalar values and length-1 arrays differently when parsing into R
* add options when reading/writing to turn this behviour on.  Probably off by default?

**Comment by coolbutuseless** [comment]
@gergness  Please have a look at latest code 

I've added an argument when parsing: `length1_array_asis` which will tag length-1 JSON arrays with the class `AsIs` in R.

I've also added `AsIs` class handling when serializing.  So you can now do a round-trip!

I have some tests for this, but would appreciate any feedback you have.

``` r
library(yyjsonr)
read_json_str('{"a":1, "b":[2]}', length1_array_asis = TRUE) |>
  write_json_str(auto_unbox = TRUE) |>
  cat()
#> {"a":1,"b":[2]}
```

<sup>Created on 2023-09-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by coolbutuseless** [comment]
@gergness any chance this suits your needs?

**Comment by coolbutuseless** [comment]
Length1 AsIs handling working ok for me.  No response from original submitter @gergness .  Closing.
