### ISSUE TITLE
Feature request: digit support

### ISSUE THREAD

**Issue by ggggeo** [coolbutuseless/yyjsonr#15]
It would be helpful for yyjsonr to support a digit/precision parameter to indicate how numeric values come out in the JSON output. Currently you can do this by ensuring the field type is integer, but this can be messy in nested data frames. Ideally something like
`digits = 0` _(integer)_
`digits = 1` _(decimal with one place)_
etc.

Alternatively, for my use case, I really just need numeric to come out as integer values, so an option to force numbers to integers would work for me. eg,
`force_int = TRUE`

**Comment by coolbutuseless** [comment]
Thanks for raising this issue.

Notes:
-  yyjsonr has no inbuilt rounding
- have to add manually rounding
- default to digits = null. I e. Do no rounding
- digits = 0 will round everything to integers.
- there are quite a few places where floating point values are written. Have to change all.
- add option to R and the main options struct in c

**Comment by coolbutuseless** [comment]
Implemented in dfd50362f32d2225fa181eb68ad9a5cd8eec0b97

@ggggeo Could you try with `digits = 0` with your use case and see if it meets you needs?

**Comment by coolbutuseless** [comment]
The `digits` option was implemented. Working Ok for me.  No response from original submitter @ggggeo . Closing.
