### ISSUE TITLE
Comparison with Arrow?

### ISSUE THREAD

**Issue by krlmlr** [coolbutuseless/yyjsonr#17]
Arrow can also read JSON, how fast/slow is it compared to this package?

**Comment by coolbutuseless** [comment]
Thanks for the tip.

Worth a look if anyone has the time to benchmark.

**Comment by coolbutuseless** [comment]
the arrow json reader seems to be ndjson only.   about 50% of the speed of yyjsonr for my usuall benchmark (reading 1000 rows of nycflights data from file)
