### ISSUE TITLE
devel R repository

### ISSUE THREAD

**Issue by jangorecki** [coolbutuseless/yyjsonr#22]
Package could benefit for extra testing (in downstream deps) if devel R repo will be provided. Aside from easier installations obviously.

If there is a will to provide one, then I can submit PR for GHA to publish devel R repo.

**Comment by coolbutuseless** [comment]
My apologies, but i'm not sure on what you're proposing to do here?

**Comment by jangorecki** [comment]
To publish development version of a package in CRAN-like repository. Then users can switch to having it inside their package distribution chain by simply setting `options(repos = c(cran_url, yyjsonr_url))`. They can easily start to import yyjsonr in their packages, without needing yyjsonr to be on CRAN, and still pass R CMD check.

**Comment by coolbutuseless** [comment]
I think for now it will just be CRAN, r-universe or github for installations.  Cheers.
