### ISSUE TITLE
FR: support json.gz

### ISSUE THREAD

**Issue by ramiromagno** [coolbutuseless/yyjsonr#27]
As always, great package! 

It would be nice if compressed files, e.g. json.gz, were handled automatically by `read_json_file()`.

**Comment by coolbutuseless** [comment]
Unfortunately, the 'yyjson' C library does not currently allowing reading directly from gzipped files.

For now, you can use an R connection objection to read from compressed streams (as below).

```
con <- gzfile("examples/test.json.gz")
js2 <- read_json_conn(con)
close.connection(con)
```

**Comment by coolbutuseless** [comment]
Proposed fix:

* add new C function `read_json_file_gz`
* link to `zlib.h`
* Detect gz filenames when callling "read_json_file" and call appropriate function
* Determine uncompressed size
* Alloc buffer
* Read in entire gzfile to memory
* Read json from buffer
* free buffer

**Comment by coolbutuseless** [comment]
Added in https://github.com/coolbutuseless/yyjsonr/commit/366f648582cd2cf83c3a799c7859ef97c810d5e5

Please have a go.   `read_file_json()` will now uncompress any file with a ".gz" suffix and then parse it.
