### ISSUE TITLE
Suggestion: propose integration into {httr2}

### ISSUE THREAD

**Issue by francisbarton** [coolbutuseless/yyjsonr#28]
Sorry if this isn't the right time or place to post this - it's more of an issue for httr2 than for here.

But to explain: currently [httr2 uses](https://httr2.r-lib.org/reference/resp_body_raw.html) {jsonlite} to parse JSON returns from APIs. Once this package is stable, it might be good to suggest to the httr2 developers (Hadley is lead I think?) that they could build around yyjsonr instead, for speed reasons.

**Comment by coolbutuseless** [comment]
It's very early days for this pkg.   "jsonlite" is a rock-solid, well-tested, stable JSON parsing package, and it wouldn't be sensible for something like httr to switch over.

Also, it's up to httr people what JSON parser they want to use, not me!

**Comment by francisbarton** [comment]
Of course - apologies

**Comment by coolbutuseless** [comment]
No apologies necessary!  Thanks for your idea!
