### ISSUE TITLE
bug: `read_json_str("any invalid json")` enters infinite loop

### ISSUE THREAD

**Issue by mmuurr** [coolbutuseless/yyjsonr#44]
These both result in an infinite loop at the terminal (with {yyjsonr} v0.1.20):
```
read_json_str("")
read_json_str("invalid json")
```
Instead an 'invalid JSON' error should probably by thrown?

**Comment by coolbutuseless** [comment]
I see this as well.

* `read_json_str("hello")` hangs (unexpected)
* `validate_json_str("hello")` immediately returns FALSE (expected)
* `read_json_file(tmp)` which just contains `hello` will immediately fail. (expected)

**Comment by coolbutuseless** [comment]
I believe this is now fixed in [506a608](https://github.com/coolbutuseless/yyjsonr/commit/506a608f59dfe16a5e568293583720ab5af3e261)

Could you confirm it is now working as expected for you?

**Comment by mmuurr** [comment]
@coolbutuseless confirmed, 506a608 errs (as expected).
