### ISSUE TITLE
Bug: `validate_json_str("foo")` works fine (returns FALSE) but seems to get stuck/hang when `validate_json_str("foo", verbose = TRUE)` is called

### ISSUE THREAD

**Issue by jrwishart** [coolbutuseless/yyjsonr#47]
I suspect this is very related to https://github.com/coolbutuseless/yyjsonr/issues/44 but the following will cause the R prompt to fill the screen with endless whitespace
```
validate_str_json("", verbose = TRUE)
validate_str_json("foo", verbose = TRUE)
```

**Comment by coolbutuseless** [comment]
Could you install from GitHub and see what happens for you? 
 Thanks

**Comment by jrwishart** [comment]
It works! I should've tried that first, was using the CRAN version. Thanks for the quick reply.
