### ISSUE TITLE
a stab at hex stickers

### ISSUE THREAD

**Issue by hrbrmstr** [coolbutuseless/yyjsonr#5]
![yyjsonr-logo](https://github.com/coolbutuseless/yyjsonr/assets/509878/252851ef-0469-4f73-bcdb-84c2f17868f4)
![yyjsonr-logo](https://github.com/coolbutuseless/yyjsonr/assets/509878/88875b22-c9b3-4719-8852-0544b793d8a8)

**Comment by hrbrmstr** [comment]
ugh i gotta downgrade the SVG. one sec

**Comment by hrbrmstr** [comment]
![](https://rud.is/dl/yyjsonr.svg)

**Comment by tanho63** [comment]
_wonders if there's an inside joke somewhere re: eight sides_

**Comment by hrbrmstr** [comment]
oh gosh
