### ISSUE TITLE
how to make sure the list to json output is a real json?

### ISSUE THREAD

**Issue by rdatasculptor** [coolbutuseless/yyjsonr#50]
first of all thank you very mucht for this promising package! It seems way faster than jsonlite. For some of my projects that is a game changer.

Perhaps I missed something, but how can I make sture the output of a list to json conversion gives back a real json?

Let's compare jsonline with yyjsonr to show what I mean. 

first make a list:
```
listExample <- list(this = "a", 
                    cool = "but", 
                    useless = "example")
```

Turn this list into a json with jsonlite:
```
jsonlite::toJSON(
  listExample,
  auto_unbox = TRUE,
  pretty = FALSE,
  force = TRUE,
  null = "null"
)
```
The output is: as expected a json:
`{"this":"a","cool":"but","useless":"example"} `

But how to do this in yyjsonr? When I do this:
```
yyjsonr::write_json_str(listExample,  
                        opts = yyjsonr::opts_write_json(auto_unbox = TRUE))
```
'
the output is:
`[1] "{\"this\":\"a\",\"cool\":\"but\",\"useless\":\"example\"}"`

So it is just a character value . How to make sure to let the outcome be a real json like jsonlite does?

Many thanks in advance

Edit: I guess I can put `cat()` around it, but when I do this:
```
json <- cat(yyjsonr::write_json_str(listExample,  
                        opts = yyjsonr::opts_write_json(auto_unbox = TRUE)))
```
json is NULL

**Comment by trafficonese** [comment]
I think you just have to define the class of the result.
This should work:
```
res <- yyjsonr::write_json_str(listExample,  
                        opts = yyjsonr::opts_write_json(auto_unbox = TRUE))
class(res) <- "json"
res
```
