### ISSUE TITLE
Rounded numbers are not always preserved during JSON serialization

### ISSUE THREAD

**Issue by OlaCaster** [coolbutuseless/yyjsonr#56]
The behaviour I would expect from any serializer is that if I first round a floating number in R and then serialize without any rounding, the number in the JSON output should remain the same. In `yyjsonr` this seems to almost always be true, although there are exceptions. Consider this simple example:

```r
x <- data.frame(orig = c(5.48860455628985e-21, 6.48893437251115e-20, 7.73083965544223e-20))
x$rounded <- signif(x$orig, 4L)
```

In R, the `rounded` column now contains 4 significant digits for all rows:

```
> x
          orig   rounded
1 5.488605e-21 5.489e-21
2 6.488934e-20 6.489e-20
3 7.730840e-20 7.731e-20
```

However, if I serialize this with `digits=-1`, the second and third rows get a lot of extra decimals added in the JSON:

```
> cat(yyjsonr::write_json_str(x, digits=-1L, auto_unbox=FALSE, num_specials="string", pretty=TRUE))
[
  {
    "orig": 5.48860455628985e-21,
    "rounded": 5.489e-21
  },
  {
    "orig": 6.48893437251115e-20,
    "rounded": 6.489000000000001e-20
  },
  {
    "orig": 7.73083965544223e-20,
    "rounded": 7.731000000000001e-20
  }
]
```

And this is despite the fact that the first and second rows both end in 489 after rounding.

**Comment by coolbutuseless** [comment]
Hi @OlaCaster 

What you are seeing here is a limitation of floating point numbers and their default presentation in R.

If you print out the numbers in R with more digits, you'll find that they actually match what ends up in the JSON.

This is just one of the many pitfalls with floating point representation - e.g. there is no exact double precision representation of the number "6.489"

This site is a fun way to explore the actual representation of floating point numbers: https://float.exposed/0x4019f4bc6a7ef9dc



``` r
x <- data.frame(orig = c(5.48860455628985e-21, 6.48893437251115e-20, 7.73083965544223e-20))
x$rounded <- signif(x$orig, 4L)

formatC(x$rounded, digits = 16)
#> [1] "        5.489e-21"     "6.489000000000001e-20" "7.731000000000001e-20"
```

<sup>Created on 2024-10-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by OlaCaster** [comment]
Thanks for the clarification!
